spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:equiposdb
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
  security:
    jwt.secret: jwtgrupo5
    jwt.expiration: 36000